// <auto-generated>
//   This code file has automatically been added by the "Aragas.Coroutines" NuGet package (https://www.nuget.org/packages/Aragas.Coroutines).
//   Please see https://github.com/Aragas/Coroutines for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "Aragas.Coroutines" folder and the "AsyncCoroutines.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated

/*

MIT License

Copyright (c) 2017-2022 Chevy Ray Johnston, Aragas

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
#pragma warning disable
namespace Coroutines
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Threading;
    using global::System.Threading.Tasks;

    /// <summary>
    /// A container for running multiple routines in parallel. Coroutines can be nested.
    /// </summary>
    public sealed class AsyncCoroutineRunner
    {
        // Avoiding using System.Linq.Async
        private sealed class EmptyAsyncIterator<TValue> : IAsyncEnumerable<TValue>, IAsyncEnumerator<TValue>, IAsyncDisposable
        {
            public static readonly EmptyAsyncIterator<TValue> Instance = new EmptyAsyncIterator<TValue>();

            public TValue Current => default;

            public ValueTask<bool> MoveNextAsync() => new ValueTask<bool>(result: false);

            public IAsyncEnumerator<TValue> GetAsyncEnumerator(CancellationToken cancellationToken)
            {
                cancellationToken.ThrowIfCancellationRequested();
                return this;
            }

            public ValueTask DisposeAsync() => default;
        }

        private readonly List<IAsyncEnumerator<object?>> _running = new();
        private readonly List<float> _delays = new();

        /// <summary>
        /// How many coroutines are currently running.
        /// </summary>
        public int Count => _running.Count;

        /// <summary>
        /// Run a coroutine.
        /// </summary>
        /// <returns>A handle to the new coroutine.</returns>
        /// <param name="delay">How many seconds to delay before starting.</param>
        /// <param name="routine">The routine to run.</param>
        public ValueTask<AsyncCoroutineHandle> RunAsync(float delay, IAsyncEnumerator<object?> routine)
        {
            _running.Add(routine);
            _delays.Add(delay);
            return new ValueTask<AsyncCoroutineHandle>(new AsyncCoroutineHandle(this, routine));
        }

        /// <summary>
        /// Run a coroutine.
        /// </summary>
        /// <returns>A handle to the new coroutine.</returns>
        /// <param name="routine">The routine to run.</param>
        public ValueTask<AsyncCoroutineHandle> RunAsync(IAsyncEnumerator<object?> routine) => RunAsync(0f, routine);

        /// <summary>
        /// Stop the specified routine.
        /// </summary>
        /// <returns>True if the routine was actually stopped.</returns>
        /// <param name="routine">The routine to stop.</param>
        public ValueTask<bool> StopAsync(IAsyncEnumerator<object?> routine)
        {
            var i = _running.IndexOf(routine);
            if (i < 0)
                return new ValueTask<bool>(false);
            _running[i] = EmptyAsyncIterator<object?>.Instance;
            _delays[i] = 0f;
            return new ValueTask<bool>(true);
        }

        /// <summary>
        /// Stop the specified routine.
        /// </summary>
        /// <returns>True if the routine was actually stopped.</returns>
        /// <param name="handle">The routine to stop.</param>
        public ValueTask<bool> StopAsync(in AsyncCoroutineHandle handle) => StopAsync(handle.Enumerator);

        /// <summary>
        /// Stop all running routines.
        /// </summary>
        public ValueTask StopAllAsync()
        {
            _running.Clear();
            _delays.Clear();

            return new ValueTask();
        }

        /// <summary>
        /// Check if the routine is currently running.
        /// </summary>
        /// <returns>True if the routine is running.</returns>
        /// <param name="routine">The routine to check.</param>
        public ValueTask<bool> IsRunningAsync(IAsyncEnumerator<object?> routine) => new ValueTask<bool>(_running.Contains(routine));

        /// <summary>
        /// Check if the routine is currently running.
        /// </summary>
        /// <returns>True if the routine is running.</returns>
        /// <param name="handle">The routine to check.</param>
        public ValueTask<bool> IsRunningAsync(in AsyncCoroutineHandle handle) => IsRunningAsync(handle.Enumerator);

        /// <summary>
        /// Update all running coroutines.
        /// </summary>
        /// <returns>True if any routines were updated.</returns>
        /// <param name="deltaTime">How many seconds have passed sinced the last update.</param>
        public async ValueTask<bool> UpdateAsync(float deltaTime)
        {
            if (_running.Count > 0)
            {
                for (var i = 0; i < _running.Count; i++)
                {
                    if (_delays[i] > 0f)
                        _delays[i] -= deltaTime;
                    else if (_running[i] == null || !await MoveNextAsync(_running[i], i))
                    {
                        _running.RemoveAt(i);
                        _delays.RemoveAt(i--);
                    }
                }
                return true;
            }
            return false;
        }

        private async ValueTask<bool> MoveNextAsync(IAsyncEnumerator<object?> routine, int index)
        {
            if (routine.Current is IAsyncEnumerator<object?> current)
            {
                if (await MoveNextAsync(current, index))
                    return true;

                _delays[index] = 0f;
            }

            var result = await routine.MoveNextAsync();

            if (routine.Current is float routineCurrent)
                _delays[index] = routineCurrent;

            return result;
        }
    }

    /// <summary>
    /// A handle to a (potentially running) coroutine.
    /// </summary>
    public readonly struct AsyncCoroutineHandle
    {
        /// <summary>
        /// Reference to the routine's runner.
        /// </summary>
        internal readonly AsyncCoroutineRunner Runner;

        /// <summary>
        /// Reference to the routine's enumerator.
        /// </summary>
        internal readonly IAsyncEnumerator<object?> Enumerator;

        /// <summary>
        /// True if the enumerator is currently running.
        /// </summary>
        public ValueTask<bool> IsRunningAsync => Runner.IsRunningAsync(in this);

        /// <summary>
        /// Construct a coroutine. Never call this manually, only use return values from Coroutines.RunAsync().
        /// </summary>
        /// <param name="runner">The routine's runner.</param>
        /// <param name="enumerator">The routine's enumerator.</param>
        internal AsyncCoroutineHandle(AsyncCoroutineRunner runner, IAsyncEnumerator<object?> enumerator)
        {
            Runner = runner ?? throw new ArgumentNullException(nameof(runner));
            Enumerator = enumerator ?? throw new ArgumentNullException(nameof(runner));
        }

        /// <summary>
        /// Stop this coroutine if it is running.
        /// </summary>
        /// <returns>True if the coroutine was stopped.</returns>
        public async ValueTask<bool> StopAsync() => await IsRunningAsync && await Runner.StopAsync(in this);

        /// <summary>
        /// A routine to wait until this coroutine has finished running.
        /// </summary>
        /// <returns>The wait enumerator.</returns>
        public async IAsyncEnumerator<object?> WaitAsync()
        {
            while (await Runner.IsRunningAsync(in this))
                yield return null;
        }
    }
}
#pragma warning restore
#nullable restore
#endif